# Generated by Django 2.2.11 on 2020-07-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200725_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
