# Generated by Django 2.2.11 on 2020-07-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200725_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='currency',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
