# Generated by Django 3.0.7 on 2020-07-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200726_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='value',
            field=models.CharField(default='$ 0.0', max_length=20),
        ),
    ]
