# Generated by Django 3.0.7 on 2020-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200726_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='page_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraper',
            name='tobe_found',
            field=models.IntegerField(default=True),
        ),
    ]
