# Generated by Django 3.0.7 on 2020-07-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200727_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='value',
            field=models.CharField(default='n/a', max_length=20),
        ),
    ]
